name: Build Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.1"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --no-default-groups --group docs --python ${{ env.DEFAULT_PYTHON }}
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build the docs
        run: uv run --no-sync mkdocs -f docs/mkdocs.yml gh-deploy --force
