---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  release:
    name: Releasing to PyPi
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pydantic-filters
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.1"
          enable-cache: true
      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          uv version "${version}" --frozen
      - name: Build package
        run: uv build
      - name: Publish to PyPi
        run: uv publish --trusted-publishing always
