---
name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.1"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --group dev --python ${{ matrix.python }}
      - name: Run pytest
        run: uv run --no-sync pytest --cov pydantic_filters tests
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-${{ matrix.python }}
          path: .coverage

  coverage:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage data
        uses: actions/download-artifact@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.1"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --group dev --python ${{ env.DEFAULT_PYTHON }}
      - name: Process coverage results
        run: |
          uv run --no-sync coverage combine coverage*/.coverage*
          uv run --no-sync coverage xml -i
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
